spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:user-db-username}
    password: ${SPRING_DATASOURCE_PASSWORD:user-db-password}
    driver-class-name: ${DRIVER_CLASS_NAME}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    contexts: dev,test
